/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.upeu.sysbazar.vista;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import pe.edu.upeu.sysbazar.BD.CategoriaBD;
import pe.edu.upeu.sysbazar.config.Conexion;
import pe.edu.upeu.sysbazar.modelo.Categoria;


/**
 *
 * @author juan
 */
public class frmCategoriaProducto extends javax.swing.JInternalFrame {
    Connection cx;
    Statement st;
    ResultSet rs;
    String sql;
    CategoriaBD crd = new CategoriaBD();
    ArrayList<Categoria> lista = new ArrayList();
    DefaultComboBoxModel<Object> combomodel = new DefaultComboBoxModel<>();
    public frmCategoriaProducto() {
        initComponents();
        
        cargarCombo();
    }
final void cargarCombo(){
lista = crd.listarCategoria();
combomodel.addElement("Seleccionar Categoria");
cbolistarCategoria.setModel(combomodel);
for(int i=0; i<lista.size();i++){
combomodel.addElement(lista.get(i).getNombreCat());
    }
cbolistarCategoria.setModel(combomodel);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btngenerar = new javax.swing.JButton();
        cbolistarCategoria = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reporte de Productos");

        jLabel1.setText("Producto");

        btngenerar.setText("generar");
        btngenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(cbolistarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btngenerar)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngenerar)
                    .addComponent(cbolistarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarActionPerformed
        // TODO add your handling code here:
         String producto =null;
        JasperReport jasperReport = null;
        try {
            cx = Conexion.GetConexion();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCategoriaProducto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmCategoriaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        producto = cbolistarCategoria.getSelectedItem().toString();
        Map parametro = new HashMap();
        parametro.put("cat", producto);
        try{
            jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/report1.jasper"));
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametro, cx);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint,false);
            jasperViewer.setVisible(true);
            
        }catch(JRException ex){
            JOptionPane.showMessageDialog(null, "JasperReport:"+ex);
        }
    }//GEN-LAST:event_btngenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerar;
    private javax.swing.JComboBox cbolistarCategoria;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
