/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.upeu.sysbazar.vista;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pe.edu.upeu.sysbazar.BD.VentaBD;
import pe.edu.upeu.sysbazar.BD.EmpleadoBD;
import pe.edu.upeu.sysbazar.BD.ClienteBD;
import pe.edu.upeu.sysbazar.modelo.Cliente;
import pe.edu.upeu.sysbazar.modelo.Empleado;
import pe.edu.upeu.sysbazar.modelo.Venta;

/**
 *
 * @author juan
 */
public class VentaForm extends javax.swing.JInternalFrame {

   DefaultComboBoxModel<Object> modelocombo = new DefaultComboBoxModel<>();
   DefaultComboBoxModel<Object> modelocombo1 = new DefaultComboBoxModel<>();
    ArrayList<Empleado> listaE;
     ArrayList<Cliente> listaC;
    
    ArrayList<Venta> lista;
    EmpleadoBD emp = new EmpleadoBD();
    ClienteBD cli = new ClienteBD();
    VentaBD ven = new VentaBD();
    DefaultTableModel model;
    DefaultListModel modelolista =  new DefaultListModel();
    public VentaForm() {
        initComponents();
        cargarEmpleado();
        cargarCliente();
        listarVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCodDocument = new javax.swing.JTextField();
        cboEmpleado = new javax.swing.JComboBox();
        txtidEmpleado = new javax.swing.JTextField();
        txtTipoDocument = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidVenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboCliente = new javax.swing.JComboBox();
        txtidCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jdFecha = new com.toedter.calendar.JDateChooser();
        txtHora = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenta = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnNuevo1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        btnagregar1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos dela Venta"));

        jLabel3.setText("Cod Documento ");

        cboEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmpleadoActionPerformed(evt);
            }
        });

        txtidEmpleado.setEnabled(false);

        jLabel5.setText("Tipo Docmento");

        jLabel6.setText("Fecha");

        jLabel8.setText("Id Venta:");

        txtidVenta.setEditable(false);

        jLabel1.setText("empleado");

        jLabel2.setText("cliente");

        cboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClienteActionPerformed(evt);
            }
        });

        txtidCliente.setEnabled(false);

        jLabel4.setText("Hora");

        jdFecha.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addComponent(cboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTipoDocument, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addComponent(txtCodDocument, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodDocument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTipoDocument, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Ventas"));

        tbVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "idEmpleado", "idCliente", "Fecha", "Hora", "Cod_Doc", "Tipo_Doc"
            }
        ));
        tbVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVenta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("OPERACIONES"));

        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        btnNuevo1.setText("NUEVO");
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete.png"))); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnModificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modify.png"))); // NOI18N
        btnModificar1.setText("MODIFICAR");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Search.png"))); // NOI18N
        btnBuscar1.setText("BUSCAR");

        btnagregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Save.png"))); // NOI18N
        btnagregar1.setText("AGREGAR");
        btnagregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnagregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnagregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar1)
                .addGap(11, 11, 11)
                .addComponent(btnBuscar1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmpleadoActionPerformed
        // TODO add your handling code here:
       String c = cboEmpleado.getSelectedItem().toString();
        int id;
        int e = cboEmpleado.getSelectedIndex();
        if(e>0){
            id = emp.DevolverIdEmpleado(c);
            txtidEmpleado.setText(""+id);
        }
    }//GEN-LAST:event_cboEmpleadoActionPerformed

    private void cboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteActionPerformed
       String cl = cboCliente.getSelectedItem().toString();
        int id;
        int x = cboCliente.getSelectedIndex();
        if(x>0){
            id = cli.DevolverIdCliente(cl);
            txtidCliente.setText(""+id);
    }//GEN-LAST:event_cboClienteActionPerformed
    }
    private void tbVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVentaMouseClicked
        if(evt.getButton()==1){
            int fila = tbVenta.getSelectedRow();
            int celda = (int) tbVenta.getValueAt(fila, 0);
            lista = ven.listarVenta(celda);
            for(int i=0;i<lista.size();i++){
                txtidEmpleado.setText(""+lista.get(i).getIdemp());
                txtidCliente.setText(""+lista.get(i).getIdcli());
                txtidVenta.setText(""+lista.get(i).getIdVenta());
                jdFecha.setDate(lista.get(i).getFecha());
                txtHora.setText(""+lista.get(i).getHora());
                txtCodDocument.setText(""+lista.get(i).getCod_doc());
                txtTipoDocument.setText(""+lista.get(i).getTipo_dog());

            }
        }
    }//GEN-LAST:event_tbVentaMouseClicked

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        limpiar(); // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        int fila = tbVenta.getSelectedRow();
        if(fila<0){
            JOptionPane.showMessageDialog(null, "Seleccionar LA VENTAo a ELIMINAR");
        }else{
            int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea ELIMINAR el Usuario? ");
            if(JOptionPane.OK_OPTION==confirmar) {
                int celda = (int) tbVenta.getValueAt(fila, 0);
                int x = ven.eliminarVenta(celda);
                if(x==1){
                    JOptionPane.showMessageDialog(null, "VENTA ELIMINADA!");
                    updateComponets();
                    limpiar();
                }else{
                    JOptionPane.showMessageDialog(null, "VENTA NO ELIMINADO!");
                }
            }

        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        int fil = tbVenta.getSelectedRow();
        if(fil<0){
            JOptionPane.showMessageDialog(null, "Seleccionar El Venta a MODIFICAR!");
        }else{
            int confirmar=JOptionPane.showConfirmDialog(null, "Esta seguro que desea MODIFICAR el venta? ");
            if(JOptionPane.OK_OPTION==confirmar) {
                int id = Integer.parseInt(txtidVenta.getText());
                int idc = Integer.parseInt(txtidCliente.getText());
                int ide = Integer.parseInt(txtidEmpleado.getText());
                String fec = jdFecha.getDateFormatString();
                 String hora = txtHora.getText();
                 int cod_doc = Integer.parseInt(txtCodDocument.getText());
                 String tipo_doc = txtTipoDocument.getText();
                int x = ven.modificarVenta(id,idc,ide, fec, hora,cod_doc,tipo_doc);

                if(x==1){
                    JOptionPane.showMessageDialog(null, "Venta MODIFICADO!");
                    updateComponets();
                    limpiar();

                }else{
                    JOptionPane.showMessageDialog(null, "Producto no se ha MODIFICADO!");
                }
            }
        }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnagregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar1ActionPerformed
        // TODO add your handling code here:
        if(cboCliente.getSelectedIndex()!=0||cboEmpleado.getSelectedIndex()!=0){
            int idc = Integer.parseInt(txtidCliente.getText());
            int ide = Integer.parseInt(txtidEmpleado.getText());
            String fecha = ((JTextField)jdFecha.getDateEditor().getUiComponent()).getText();
            String hora = txtHora.getText();
            int cod_doc =Integer.parseInt( txtCodDocument.getText());
            String tipo_doc=txtTipoDocument.getText();
            int v = ven.registrarVenta(idc,ide,fecha,hora,cod_doc,tipo_doc);
            
            limpiar();
            if(v >0){
                JOptionPane.showMessageDialog(this, "Exitoso");}
            updateComponets();

        }else{
            JOptionPane.showMessageDialog(this, "Seleccionar cliente");
        }
    }//GEN-LAST:event_btnagregar1ActionPerformed
final void cargarCliente(){
 listaC = cli.listarCliente();
 cboCliente.setModel(modelocombo1);
 modelocombo1.addElement("Cargar Cliente");
 for(int i=0;i<listaC.size();i++){
     modelocombo1.addElement(listaC.get(i).getNombres());
 }
cboCliente.setModel(modelocombo1);
}
final void cargarEmpleado(){
 listaE = emp.listarEmpleado();
 cboEmpleado.setModel(modelocombo);
 modelocombo.addElement("Cargar Empleado");
 for(int i=0;i<listaE.size();i++){
     modelocombo.addElement(listaE.get(i).getNombres());
 }
cboCliente.setModel(modelocombo);
}
void limpiar(){
txtHora.setText(null);
txtCodDocument.setText(null);
txtTipoDocument.setText(null);
txtidCliente.setText(null);
txtidEmpleado.setText(null);
txtidVenta.setText(null);
cboCliente.setSelectedIndex(0);
cboEmpleado.setSelectedIndex(0);
jdFecha.setDate(null);
}
final void listarVenta(){
    lista = ven.listarVenta();
    model = (DefaultTableModel) tbVenta.getModel();
        Object[] vent = new Object[7];
        for(int i=0;i<lista.size();i++){
            vent[0]=lista.get(i).getIdVenta();
            vent[1]=lista.get(i).getIdemp();
            vent[2]=lista.get(i).getIdcli();
            vent[3]=lista.get(i).getFecha();
            vent[4]=lista.get(i).getHora();
            vent[5]=lista.get(i).getCod_doc();
            vent[6]=lista.get(i).getTipo_dog();
            model.addRow(vent);
        }        
        tbVenta.setModel(model);
}
void LimpiarTabla(DefaultTableModel modelo){
        int a =modelo.getRowCount()-1;
        for(int i=a;i>=0;i--){  
            modelo.removeRow(i);
        }
 }

 void updateComponets(){
            LimpiarTabla(model);
            listarVenta();
            modelocombo.removeAllElements();
            cargarComboc();
            cargarComboe();
            modelolista.clear();
            cargarList(); 
    }
 
 void cargarComboc(){
   
    listaC = cli.listarCliente();
    modelocombo.addElement("Seleccionar Cliente");
    cboCliente.setModel(modelocombo);
        for(int i=0;i<listaC.size();i++){
            modelocombo.addElement(listaC.get(i).getNombres());
            cboCliente.setModel(modelocombo);
        }
    
 }
 
 void cargarComboe(){
   
    listaE = emp.listarEmpleado();
    modelocombo.addElement("Seleccionar Empleado");
    cboEmpleado.setModel(modelocombo);
        for(int i=0;i<listaE.size();i++){
            modelocombo.addElement(listaE.get(i).getNombres());
            cboEmpleado.setModel(modelocombo);
        }
    
 }
 void cargarList(){
   
    lista = ven.listarVenta();
    //lsUsuario.setModel(modelolista);
        for(int i=0;i<lista.size();i++){
            modelolista.addElement(lista.get(i).getFecha());
            //lsUsuario.setModel(modelolista);
        }
    
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton btnagregar1;
    private javax.swing.JComboBox cboCliente;
    private javax.swing.JComboBox cboEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JTable tbVenta;
    private javax.swing.JTextField txtCodDocument;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtTipoDocument;
    private javax.swing.JTextField txtidCliente;
    private javax.swing.JTextField txtidEmpleado;
    private javax.swing.JTextField txtidVenta;
    // End of variables declaration//GEN-END:variables
}
